"""
uncertain_phys.py — the PHYSICS-BASED generalized plant for mu-synthesis.
=========================================================================
Same synthesis method as Du et al. (2024) -- the D-K iteration of Eqs. (28)-(29),
the same additive weights W_Paf, W_Pau of Eqs. (18)-(19), the same performance
weights W_Pf, W_Pu, W_Pn, the same actuator, sensor and operating point.  The
ONLY thing that changes is the uncertainty description, i.e. Eqs. (22)-(25).

    Eqs. (22)-(25)                    this module
    ------------------------------    -----------------------------------------
    10 INDEPENDENT real scalars       6 real parameters, three of them repeated
    d_Pm1 d_Pm2 d_Pc1 d_Pc2           delta_eta  (x4)  removed material
    d_Pk1 d_Pk2                       delta_xi   (x2)  mid-pass state
    d_PD1 d_PD2 d_PD3 d_PD4           delta_D    (x2)  tool position (direction)
                                      delta_a    (x1)  milling-force coefficient
                                      delta_z1, delta_z2  modal damping ratio
    a symmetric +/-10 % / +/-20 % box  eta in [0, eta_max]: ONE-SIDED, so the
    centred on the un-machined plate   nominal is the mid-removal plate and the
                                       radius is halved
    DM, DC, DK independent             all three are functions of the SAME eta
    D_PrD: four free entries, so       W = a d(x) d(x)^T is kept EXACTLY rank
    the perturbed cutting stiffness    one, symmetric and sign-definite for
    is neither symmetric, nor rank     every value of the parameters
    one, nor sign-definite

Three structural facts of the plant are therefore imposed on the uncertainty set
instead of being thrown away:

  S1 (correlation)   M, C and K are generated by ONE scalar, the removed volume
                     fraction eta.  The Ritz integrals are additive over the
                     domain, so eta moves all three together; six independent
                     scalars describe a set whose physical image is a curve.
  S2 (one-sidedness) material is removed, never added:  DM <= 0, DK <= 0 in the
                     Loewner order.  Half of any symmetric box is unreachable.
  S3 (rank one)      the cutting stiffness is a * D(x)^T D(x) with D(x) a single
                     row -- rank one, symmetric, and of the sign of a, at every
                     tool position.

Representation.  eta enters M, C, K through the Ritz integrals; a quadratic in
delta_eta reproduces that dependence to 0.25 % of the perturbation amplitude
(measured, see `fit_report`), and a quadratic is represented EXACTLY by a real
scalar repeated twice on a chained channel.  The tool position enters through
the single row d(x), whose locus in R^2 is a straight line to 2 % (two singular
values, 83.4 and 1.94), so d = d_c + delta_D l_1 + delta_r l_2 covers it with a
rectangle; the resulting W stays rank one for every point of that rectangle.

Block list handed to `dk_synthesis.dk_iteration`:

    [('F',2,1)]                       Delta_Pa, additive truncation error
    ('S',4,4) delta_eta               removed material   (M, C, K together)
    ('S',2,2) delta_xi                mid-pass state
    ('S',2,2) delta_D                 tool position, principal direction
    ('S',2,2) delta_r                 tool position, residual direction
    ('S',1,1) delta_a                 milling-force coefficient (Eq. 23 range)
    ('S',1,1) delta_z1, ('S',1,1) delta_z2   damping ratios (+/-20 %)
    [('P',2,2)]                       performance

A repeated real block is given a SCALAR D-scale by `dk_synthesis` (one per
block), not the full matrix an exact repeated-block bound would allow; that is
conservative, so the mu reported here is an upper bound of the upper bound.
`mu_tight` recomputes the peak with full-matrix D-scales for the final design.
"""
import numpy as np

import config as C
from milling_dynamics import alpha4_average, AE_NOM
from weights import W_Paf_ss, W_Pau_ss, synthesis_weights
from uncertainty import RemovalFamily


# ---------------------------------------------------------------------------
def removal_fit(fam, eta_max, d_eta, n_grid=21):
    """Quadratic model of (M, C, K) in eta, plus the mid-pass (xi) offset.

    The fit is made on the END-OF-PASS branch xi = 1, which is the smooth one
    (the current-pass rectangle has its full depth there).  Removing the pass in
    progress can only ADD material back, so for every eta

        X(eta, 1)  <=  X(eta, xi)  <=  X(eta, 0)      (Loewner order, T2),

    i.e. the mid-pass states occupy a ONE-SIDED interval of width `spread`.  It
    is therefore represented, like eta itself, by a centred parameter of HALF
    that width -- never by a symmetric interval about the end-of-pass state.

    Returns  {M: [X0, Xa, Xb], Mx: half-spread, ...}  with
        X(eta, xi) = X0 + eta Xa + eta^2 Xb + Xx  +  delta_xi Xx ,  |delta_xi|<=1.
    """
    g = np.linspace(0.0, eta_max, n_grid)
    S = {k: [] for k in ('M', 'C', 'K')}
    Sx = {k: [] for k in ('M', 'C', 'K')}
    for e in g:
        M0_, C0_, K0_ = fam.matrices(e, xi=0.0, z=1.0, d_eta=d_eta)
        M1_, C1_, K1_ = fam.matrices(e, xi=1.0, z=1.0, d_eta=d_eta)
        S['M'].append(M1_); Sx['M'].append(0.5 * (M0_ - M1_))
        S['C'].append(C1_); Sx['C'].append(0.5 * (C0_ - C1_))
        S['K'].append(K1_); Sx['K'].append(0.5 * (K0_ - K1_))
    V = np.vander(g, 3, increasing=True)
    out, rep = {}, {}
    for k in ('M', 'C', 'K'):
        Y = np.array(S[k]).reshape(n_grid, -1)
        co, *_ = np.linalg.lstsq(V, Y, rcond=None)
        res = Y - V @ co
        out[k] = list(co.reshape(3, *np.array(S[k]).shape[1:]))
        amp = np.abs(out[k][1] * eta_max).max()
        rep[k] = dict(resid=float(np.abs(res).max()),
                      rel_amp=float(np.abs(res).max() / max(amp, 1e-30)),
                      rel_nom=float(np.abs(res).max()
                                    / max(np.abs(np.array(S[k])[0]).max(), 1e-30)))
        out[k + 'x'] = np.max(np.abs(np.array(Sx[k])), axis=0)
    return out, rep


def direction_rectangle(plate, n=2, n_x=201):
    """d_c, l_1, l_2 such that  { D(x) : x in [0, l_P] }  is inside the rectangle
    d_c + [-1,1] l_1 + [-1,1] l_2, with l_1 the principal direction of the locus.

    Every point of the rectangle gives a rank-one, symmetric  W = a d d^T, which
    is what Eq. (25) -- four free entries of a 2x2 matrix -- does not.
    """
    xs = np.linspace(0.0, plate.lp, n_x)
    D = np.array([plate.D_row(x, plate.hp)[:n] for x in xs])
    dc = 0.5 * (D.max(0) + D.min(0))
    Y = D - dc
    _, sv, Vt = np.linalg.svd(Y, full_matrices=False)
    t1, t2 = Y @ Vt[0], Y @ Vt[1]
    l1 = Vt[0] * np.abs(t1).max()
    l2 = Vt[1] * np.abs(t2).max()
    return dc, l1, l2, dict(sv=sv, x=xs, D=D, cover=float(sv[1] / sv[0]))


# ---------------------------------------------------------------------------
class PhysUncertainSystem:
    """Generalized plant G_Pmu built on the physics-based uncertainty set."""

    #  multiplicities: d_D and d_r act on the cutting stiffness (twice) AND on
    #  the direction of the cutting FORCE itself, which is alpha_3 D(x)^T -- the
    #  same row.  A fixed disturbance direction beside an uncertain stiffness
    #  direction would be inconsistent, so with `unc_force` they get a third
    #  repetition instead of a frozen nominal row.
    BLOCKS = [('d_eta', 4), ('d_xi', 2), ('d_D', 3), ('d_r', 3),
              ('d_a', 1), ('d_z1', 1), ('d_z2', 1)]
    BLOCKS_FIXED_F = [('d_eta', 4), ('d_xi', 2), ('d_D', 2), ('d_r', 2),
                      ('d_a', 1), ('d_z1', 1), ('d_z2', 1)]

    def __init__(self, plate, rpm, ap, ae=AE_NOM, n_modes=2, one_sided=True,
                 eta_max=None, zeta_pert=0.20, wpf=None, wpu=None, wpn=None,
                 x_obs=None, z_obs=None, sign=1.0, correlated=True,
                 unc_force=True):
        self.plate, self.rpm, self.ap, self.ae = plate, rpm, ap, ae
        self.n = n = n_modes
        self.sign = float(sign)
        self.one_sided = bool(one_sided)
        self.correlated = bool(correlated)
        self.unc_force = bool(unc_force)
        self.eta_max = C.ETA_MAX if eta_max is None else float(eta_max)
        self.zeta_pert = float(zeta_pert)

        self.fam = RemovalFamily(n=n)
        self.d_eta = ap / plate.hp
        fit, rep = removal_fit(self.fam, self.eta_max, self.d_eta)
        self.fit, self.fit_report = fit, rep

        # ---- eta -> delta.  one-sided: eta = eta_max (1+d)/2, so the NOMINAL is
        # the mid-removal plate and the radius is eta_max/2 instead of eta_max.
        h = self.eta_max / 2.0 if one_sided else self.eta_max
        e0 = h if one_sided else 0.0
        for k in ('M', 'C', 'K'):
            X0, Xa, Xb = fit[k]
            Xx = fit[k + 'x']
            setattr(self, k + '_c', X0 + e0 * Xa + e0**2 * Xb + Xx)
            setattr(self, k + '_1', h * Xa + 2.0 * e0 * h * Xb)
            setattr(self, k + '_2', h**2 * Xb)
            setattr(self, k + '_x', Xx)

        # ---- geometry of the cutting force
        self.abar4 = alpha4_average(rpm, ap, plate.hp, ae)
        self.a0 = self.sign * 1.6 * self.abar4                    # Eq. (23)
        self.La = self.sign * 1.3 * self.abar4                    # Eq. (23)
        dc, l1, l2, ginfo = direction_rectangle(plate, n)
        self.d_c, self.l1, self.l2, self.geom = dc, l1, l2, ginfo

        # ---- actuator / sensor, identical to the paper's reproduction
        self.x_obs = plate.lp if x_obs is None else x_obs
        self.z_obs = plate.hp if z_obs is None else z_obs
        self.D_obs = plate.D_row(self.x_obs, self.z_obs)[:n]
        self.H = np.asarray(plate.H_Pe_modal, float)[:n]

        self.Wf, self.Wu, self.Wn = synthesis_weights(wpf, wpu, wpn)
        self.Waf, self.Wau = W_Paf_ss(), W_Pau_ss()
        self._build()

    # ------------------------------------------------------------------
    @property
    def blocks_used(self):
        m = 3 if self.unc_force else 2
        b = list(self.BLOCKS if self.unc_force else self.BLOCKS_FIXED_F)
        if not self.correlated:                 # ablation: eta split per matrix
            b = [('d_M', 2), ('d_C', 2), ('d_K', 2), ('d_xi', 2), ('d_D', m),
                 ('d_r', m), ('d_a', 1), ('d_z1', 1), ('d_z2', 1)]
        return b

    def _channel_map(self):
        """Ordered list of (block name, channel tag) for the parametric part."""
        ch = []
        for name, mult in self.blocks_used:
            for j in range(mult):
                ch.append((name, j))
        return ch

    # ------------------------------------------------------------------
    def _build(self):
        """LFT of the uncertain plate.

        Equation of motion, with q the modal coordinate and z = q'' :

          [M_c + d M_1 + d^2 M_2 + dx M_x] z
        + [C_c + d C_1 + d^2 C_2 + dx C_x + diag(dz) Cz] q'
        + [K_c + d K_1 + d^2 K_2 + dx K_x] q
        + (a0 + La da) (d_c + dD l1 + dr l2)(d_c + dD l1 + dr l2)^T q
        = H u + (d_c + dD l1 + dr l2) f

        The delta_eta part is  d (u1 + d u2)  with
          u1 = M_1 z + C_1 q' + K_1 q ,   u2 = M_2 z + C_2 q' + K_2 q ,
        which is exactly two chained repetitions of one real scalar.
        """
        n = self.n
        names = [b[0] for b in self.blocks_used]
        mult = dict(self.blocks_used)
        idx, k = {}, 0
        for nm, m in self.blocks_used:
            idx[nm] = list(range(k, k + m)); k += m
        self.n_par = nu = k
        self.idx = idx

        Minv = np.linalg.inv(self.M_c)
        Kc_eff = self.K_c + self.a0 * np.outer(self.d_c, self.d_c)
        A21 = -Minv @ Kc_eff
        A22 = -Minv @ self.C_c
        A = np.block([[np.zeros((n, n)), np.eye(n)], [A21, A22]])
        Bf = np.concatenate([np.zeros(n), Minv @ self.d_c])[:, None]
        Bu = np.concatenate([np.zeros(n), Minv @ self.H])[:, None]

        # ---- how each uncertainty input feeds the acceleration --------------
        Bz = np.zeros((n, nu))
        if self.correlated:
            Bz[:, idx['d_eta'][2:4]] = -Minv                 # w_b  (= d(u1+d u2))
        else:
            for nm in ('d_M', 'd_C', 'd_K'):
                Bz[:, idx[nm]] = -Minv
        Bz[:, idx['d_xi']] = -Minv                           # w_x
        Bz[:, [idx['d_z1'][0], idx['d_z2'][0]]] = -Minv      # w_zeta
        # cutting stiffness chain
        Bz[:, idx['d_D'][0]] = -self.a0 * (Minv @ self.d_c)  # w1 -> a0 d_c w1
        Bz[:, idx['d_r'][0]] = -self.a0 * (Minv @ self.d_c)  # w2 -> a0 d_c w2
        Bz[:, idx['d_a'][0]] = -self.La * (Minv @ self.d_c)  # w3 -> La d_c w3
        Bz[:, idx['d_D'][1]] = -(Minv @ self.l1)             # w4
        Bz[:, idx['d_r'][1]] = -(Minv @ self.l2)             # w5
        if self.unc_force:
            # F_PIr enters through alpha_3 d(x)^T -- the SAME row that builds the
            # cutting stiffness -- so its direction moves with delta_D, delta_r.
            # These columns must be in place BEFORE the force channels are laid
            # out, because their D-terms are Mm @ Bz.
            Bz[:, idx['d_D'][2]] = Minv @ self.l1            # w6
            Bz[:, idx['d_r'][2]] = Minv @ self.l2            # w7
        Bunc = np.vstack([np.zeros((n, nu)), Bz])
        Bzf, Bzu = Minv @ self.d_c, Minv @ self.H

        # ---- uncertainty outputs -------------------------------------------
        Cunc = np.zeros((nu, 2 * n))
        Dun = np.zeros((nu, nu))
        Df = np.zeros((nu, 1))
        Du = np.zeros((nu, 1))

        def force_channel(rows, Km, Cm, Mm, extra=None):
            """y = Km q + Cm q' + Mm z  (z eliminated through the state eq.)."""
            Cunc[np.ix_(rows, range(n))] = Km + Mm @ A21
            Cunc[np.ix_(rows, range(n, 2 * n))] = Cm + Mm @ A22
            Dun[np.ix_(rows, range(nu))] = Mm @ Bz
            Df[rows, 0] = Mm @ Bzf
            Du[rows, 0] = Mm @ Bzu
            if extra is not None:
                for r, c in zip(rows, extra):
                    Dun[r, c] += 1.0

        if self.correlated:
            force_channel(idx['d_eta'][0:2], self.K_2, self.C_2, self.M_2)
            force_channel(idx['d_eta'][2:4], self.K_1, self.C_1, self.M_1,
                          extra=idx['d_eta'][0:2])          # y_b = u1 + w_a
        else:
            Z = np.zeros((n, n))

            def env(X1, X2):
                return np.sign(X1 + X2 + 1e-300) * np.maximum(
                    np.abs(X1 + X2), np.abs(X1 - X2))
            force_channel(idx['d_M'], Z, Z, env(self.M_1, self.M_2))
            force_channel(idx['d_C'], Z, env(self.C_1, self.C_2), Z)
            force_channel(idx['d_K'], env(self.K_1, self.K_2), Z, Z)
        force_channel(idx['d_xi'], self.K_x, self.C_x, self.M_x)

        Cz = self.zeta_pert * self.C_c
        for i, nm in enumerate(('d_z1', 'd_z2')):
            Cunc[idx[nm][0], n:] = Cz[i]

        # cutting-stiffness chain:  v = d_c^T q + w1 + w2
        #                           g = a0 v + La w3
        i1, i4 = idx['d_D'][:2]; i2, i5 = idx['d_r'][:2]
        i3 = idx['d_a'][0]
        Cunc[i1, :n] = self.l1                                   # y1 = l1^T q
        Cunc[i2, :n] = self.l2                                   # y2 = l2^T q
        Cunc[i3, :n] = self.d_c                                  # y3 = v
        Dun[i3, i1] = Dun[i3, i2] = 1.0
        for r in (i4, i5):                                       # y4 = y5 = g
            Cunc[r, :n] = self.a0 * self.d_c
            Dun[r, i1] = Dun[r, i2] = self.a0
            Dun[r, i3] = self.La
        if self.unc_force:                    # y6 = y7 = f
            Df[idx['d_D'][2], 0] = 1.0
            Df[idx['d_r'][2], 0] = 1.0

        self.ss_plant = dict(A=A, Bunc=Bunc, Bf=Bf, Bu=Bu, Cunc=Cunc,
                             Dunc_unc=Dun, Dunc_f=Df, Dunc_u=Du,
                             Cy=np.concatenate([self.D_obs,
                                                np.zeros(n)])[None, :],
                             names=self._channel_map())

    # ------------------------------------------------------------------
    def _channel_scales(self, q0=1e-6, w0=2 * np.pi * 1000.0, f0=1.0, u0=100.0):
        """Per-channel normalisation of the parametric block.

        A diagonal similarity T applied to a repeated-scalar block leaves
        Delta = delta I unchanged (diagonal matrices commute with delta I), so
        every channel of an 'S' block may be scaled on its own -- exactly the
        freedom the frozen code does not have, and the one this LFT needs
        because a single block now mixes position-like and force-like channels.
        """
        sp = self.ss_plant
        n = self.n
        sig = np.concatenate([q0 * np.ones(n), q0 * w0 * np.ones(n)])
        base = (np.abs(sp['Cunc']) @ sig + np.abs(sp['Dunc_f'][:, 0]) * f0
                + np.abs(sp['Dunc_u'][:, 0]) * u0)
        m = base.copy()
        for _ in range(50):
            m = base + np.abs(sp['Dunc_unc']) @ m
            if not np.all(np.isfinite(m)):
                m = base.copy(); break
        return 1.0 / np.maximum(m, 1e-300)

    # ------------------------------------------------------------------
    def generalized_plant(self, normalise=True):
        """Generalized plant P, laid out exactly like the paper's version.

        inputs  : [u_Pa (1) | u_Pr (n_par) | F_PIr (1) | n_P (1) | u_P (1)]
        outputs : [y_Paf, y_Pau (2) | y_Pr (n_par) | z_disp, z_u (2) | y (1)]
        states  : [q, q' (2n) | W_Paf (2) | W_Pau (2) | W_Pf (1) | W_Pu (1)]
        """
        sp = self.ss_plant
        n = self.n
        nx_p = 2 * n
        Aaf, Baf, Caf, Daf = self.Waf
        Aau, Bau, Cau, Dau = self.Wau
        Af, Bf_w, Cf, Df_w = self.Wf
        Au, Bu_w, Cu, Du_w = self.Wu
        _, _, _, Dn = self.Wn
        nz = [nx_p, Aaf.shape[0], Aau.shape[0], Af.shape[0], Au.shape[0]]
        off = np.cumsum([0] + nz)
        N = off[-1]
        nu = sp['Bunc'].shape[1]
        n_in, n_out = 1 + nu + 3, 2 + nu + 3

        A = np.zeros((N, N)); B = np.zeros((N, n_in))
        Cm = np.zeros((n_out, N)); D = np.zeros((n_out, n_in))
        i_ua, i_ur, i_f, i_np, i_up = 0, 1, 1 + nu, 2 + nu, 3 + nu
        o_af, o_au, o_ur, o_z1, o_z2, o_y = (0, 1, 2, 2 + nu, 3 + nu, 4 + nu)
        sl = [slice(off[k], off[k + 1]) for k in range(5)]

        A[sl[0], sl[0]] = sp['A']
        B[sl[0], i_ur:i_ur + nu] = sp['Bunc']
        B[sl[0], i_f:i_f + 1] = sp['Bf']
        B[sl[0], i_up:i_up + 1] = sp['Bu']
        A[sl[1], sl[1]] = Aaf; B[sl[1], i_f:i_f + 1] = Baf
        Cm[o_af, sl[1]] = Caf; D[o_af, i_f] = Daf[0, 0]
        A[sl[2], sl[2]] = Aau; B[sl[2], i_up:i_up + 1] = Bau
        Cm[o_au, sl[2]] = Cau; D[o_au, i_up] = Dau[0, 0]
        Cm[o_ur:o_ur + nu, sl[0]] = sp['Cunc']
        D[o_ur:o_ur + nu, i_ur:i_ur + nu] = sp['Dunc_unc']
        D[o_ur:o_ur + nu, i_f] = sp['Dunc_f'][:, 0]
        D[o_ur:o_ur + nu, i_up] = sp['Dunc_u'][:, 0]
        Cy = sp['Cy']
        A[sl[3], sl[3]] = Af; A[sl[3], sl[0]] = Bf_w @ Cy
        B[sl[3], i_ua:i_ua + 1] = Bf_w
        Cm[o_z1, sl[3]] = Cf; Cm[o_z1, sl[0]] = Df_w @ Cy
        D[o_z1, i_ua] = Df_w[0, 0]
        A[sl[4], sl[4]] = Au; B[sl[4], i_up:i_up + 1] = Bu_w
        Cm[o_z2, sl[4]] = Cu; D[o_z2, i_up] = Du_w[0, 0]
        Cm[o_y, sl[0]] = Cy
        D[o_y, i_ua] = 1.0
        D[o_y, i_np] = Dn[0, 0]

        blocks = ([('F', 2, 1)]
                  + [('S', m, m) for _, m in self.blocks_used]
                  + [('P', 2, 2)])
        names = ['Delta_Pa'] + [b[0] for b in self.blocks_used] + ['Delta_Pp']

        # --- per-channel similarity (allowed on repeated real blocks) --------
        g = self._channel_scales()
        dsc = [1e6]                                   # Delta_Pa: 1/q0, as before
        for nm, m in self.blocks_used:
            gi = g[self.idx[nm]]
            dsc.append(float(np.exp(np.mean(np.log(np.maximum(gi, 1e-300))))))
        t = np.ones(nu)
        for j, (nm, _) in enumerate(self.blocks_used):
            ii = self.idx[nm]
            t[ii] = g[ii] / dsc[j + 1]
        if normalise:
            rows = slice(o_ur, o_ur + nu)
            cols = slice(i_ur, i_ur + nu)
            Cm[rows, :] *= t[:, None]
            D[rows, :] *= t[:, None]
            B[:, cols] /= t[None, :]
            D[:, cols] /= t[None, :]

        return dict(A=A, B=B, C=Cm, D=D, nmeas=1, ncon=1, blocks=blocks,
                    n_unc_in=1 + nu, n_unc_out=2 + nu, n_w=2, n_z=2,
                    dscale_init=np.array(dsc), names=names,
                    channels=sp['names'])

    # ------------------------------------------------------------------
    def nominal_open_loop(self):
        sp = self.ss_plant
        return sp['A'], sp['Bf'], sp['Bu'], sp['Cy']

    # ------------------------------------------------------------------
    def sample(self, eta, xi=1.0, x_tool=None, a_mult=1.6, z=1.0):
        """(A, B_f, B_u, C_y) of the TRUE plant at a point of the physical set,
        used to check that the LFT family contains the physics."""
        n = self.n
        M, Cmat, K = self.fam.matrices(eta, xi, z, self.d_eta)
        D = self.plate.D_row(self.plate.lp if x_tool is None else x_tool,
                             self.plate.hp)[:n]
        a = self.sign * a_mult * self.abar4
        Minv = np.linalg.inv(M)
        A = np.block([[np.zeros((n, n)), np.eye(n)],
                      [-Minv @ (K + a * np.outer(D, D)), -Minv @ Cmat]])
        return (A, np.concatenate([np.zeros(n), Minv @ D])[:, None],
                np.concatenate([np.zeros(n), Minv @ self.H])[:, None],
                np.concatenate([self.D_obs, np.zeros(n)])[None, :])

    def _loop(self, delta):
        sp = self.ss_plant
        nu = sp['Bunc'].shape[1]
        dv = np.zeros(nu)
        for nm, _ in self.blocks_used:
            dv[self.idx[nm]] = delta[nm]
        Dl = np.diag(dv)
        return sp, Dl, np.linalg.inv(np.eye(nu) - Dl @ sp['Dunc_unc'])

    def lft_sample(self, delta):
        """A(delta) produced by the LFT for a given parameter vector."""
        sp, Dl, S = self._loop(delta)
        return sp['A'] + sp['Bunc'] @ S @ Dl @ sp['Cunc']

    def lft_Bf(self, delta):
        """Disturbance input direction produced by the LFT."""
        sp, Dl, S = self._loop(delta)
        return sp['Bf'] + sp['Bunc'] @ S @ Dl @ sp['Dunc_f']
